version: "3.7"
services:
  order-service-app:
    container_name: order-service-app
    build: ./order-service
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    ports:
    - "3000:3000"
    networks:
    - microservice-network
    depends_on:
      - order-service-db

  order-service-db:
    container_name: order-service-db
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: order_service
    ports:
    - "5432:5432"
    volumes:
    - order_postgres_data:/var/lib/postgresql/data
    networks:
    - microservice-network

  payment-service-app:
    container_name: payment-service-app
    build: ./payment-service
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    ports:
    - "4000:4000"
    networks:
    - microservice-network
    depends_on:
    - payment-service-db

  payment-service-db:
    container_name: payment-service-db
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: payment_service
    ports:
    - "5433:5432"
    volumes:
    - payment_postgres_data:/var/lib/postgresql/data
    networks:
    - microservice-network

volumes:
  order_postgres_data:
  payment_postgres_data:

networks:
  microservice-network:
    driver: bridge