apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          build: ../../payment-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: PAYMENT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: PAYMENT_URL
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: NodePort
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 3000
      nodePort: 30200