apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-postgres
  template:
    metadata:
      labels:
        app: order-postgres
    spec:
      containers:
        - name: order-postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: order-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: order-postgredb
      volumes:
        - name: order-postgredb
          persistentVolumeClaim:
            claimName: order-postgres-pv-claim